name: CoordinateOffset
version: "${version}"
main: com.jtprince.coordinateoffset.CoordinateOffset
api-version: "${apiVersion}"
depend: [ ProtocolLib ]
softdepend: [ LuckPerms ]
authors: [ jtprince, cavallium ]
